baseURL = "http://nameontree.github.io"
languageCode = "en-us"
title = "Myungjae Cho"
theme = "hugo-PaperMod"

[params]
  title = "Sprinkle stars"
  slogan = "gg"
  SEOTitle = "Myungjae Cho Blog"
  keyword = "Computer"
